### ISSUE TITLE
Vocab improvements

### ISSUE THREAD

**Issue by ragesoss** [MycroftAI/skill-volume#16]
I had to dig into this repository to figure out how to control the volume except one unit at a time. Here are things I tried before I looked up the right words:

* Set volume to max
* Max volume
* Increase volume to max
* Increase volume all the way

Some other things that might be good to cover:
* Turn the volume down
* Turn the volume up

**Comment by krisgesling** [comment]
Hey there, these phrases should all now work with the Volume Skill. 

Thanks for the great feedback (and apologies for the very slow response)
