### ISSUE TITLE
Cannot modify the volume to Picroft 

### ISSUE THREAD

**Issue by redviper2100** [MycroftAI/skill-volume#19]
Hi,

I copied the latest image of the Picroft for a Raspberry pi 3 B+, but I cannot set the Volume.
It seems there's a problem with the skill since i can manually set the volume from python command line.
[https://github.com/MycroftAI/enclosure-picroft/tree/stretch](url)

I get this following error:

~~~~r:716 - ERROR - An error occurred while processing a request in Volume Skill
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 707, in wrapper
handler(message)
~~~~/skills/mycroft-volume.mycroftai/__init__.py", line 95, in handle_set_volume
level = self.__get_volume_level(message, self.mixer.getvolume()[0])
AttributeError: 'VolumeSkill' object has no attribute 'mixer'

Can anybody help me?

**Comment by forslund** [comment]
Hi, can you check the skills log (`/var/log/mycroft/skills.log`) for something like

`Couldn't allocate mixer, ` followed by some sort of reason for the failure.

**Comment by forslund** [comment]
Hi again, I think I've found a workaround for this issue. I will create a PR shortly

**Comment by forslund** [comment]
You can now try the beta `hey mycroft install the beta version of the volume skill`

**Comment by krisgesling** [comment]
Hi there, we believe this issue has been resolved. Please let us know if you're still seeing issues.
