### ISSUE TITLE
Volume change doesn't work

### ISSUE THREAD

**Issue by colla69** [MycroftAI/skill-volume#41]
Hi, 

I use mycroft as an assistant on Ubuntu + KDE.
For the last couple of weeks, the volume skill hasn't been working for me.
It responds to me and apparently works fine ( there are no logged errors ), the volume of my computer isn't actually changing.

**Comment by forslund** [comment]
Hi @colla69 do you consider this issue resolved?

**Comment by krisgesling** [comment]
Hey there, I'm assuming this is resolved thanks to the merged PR.

Thanks colla69
