### ISSUE TITLE
Level param can arrive at final step as wrong data type

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/skill-volume#78]
We have not investigated in detail, but [a one-liner](https://github.com/OpenVoiceOS/skill-ovos-volume/pull/1/commits/999265875c85f6908abc12a4b740718ff6914c85) patched [a problem](https://github.com/OpenVoiceOS/skill-ovos-volume/pull/1) where a param was getting to a helper function as an int, but should have been a string.

I assume this is happening "up the chain," wherever the skill attempts to address #24, but I'm not sure.

**Comment by krisgesling** [comment]
Thanks for the heads up :)

PR linked
